"""autoDream runner — CLI entry point for nightly KAIROS memory consolidation.

Invoked by scripts/autodream.sh and cron. Loads health data and session logs,
runs AutoDreamBrain, writes updated robot-memory.md atomically, and appends
a structured entry to dream-log.jsonl.

Usage:
    python -m castor.brain.autodream_runner
    CASTOR_MODEL=claude-haiku-4-5-20251001 python -m castor.brain.autodream_runner
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import tempfile
from datetime import datetime
from pathlib import Path

from castor.brain.autodream import AutoDreamBrain, DreamResult, DreamSession
from castor.brain.autodream_issues import build_issue_template, file_github_issue

logger = logging.getLogger("OpenCastor.AutoDreamRunner")

# Cheap, fast model for nightly runs — overridable via env.
DEFAULT_MODEL = "claude-haiku-4-5-20251001"

# Set CASTOR_AUTODREAM_DRY_RUN=1 to skip actual gh issue creation.
DRY_RUN = os.getenv("CASTOR_AUTODREAM_DRY_RUN", "0") != "0"

# GitHub repo to file issues against — overridable via env.
DEFAULT_GITHUB_REPO = "craigm26/OpenCastor"

OPENCASTOR_DIR = Path.home() / ".opencastor"
MEMORY_FILE = OPENCASTOR_DIR / "robot-memory.md"
DREAM_LOG_FILE = OPENCASTOR_DIR / "dream-log.jsonl"
GATEWAY_LOG = Path("/tmp/castor-gateway.log")


def _load_health_report(date_str: str) -> dict:
    """Load health-YYYYMMDD.json; return empty dict if missing."""
    path = OPENCASTOR_DIR / f"health-{date_str.replace('-', '')}.json"
    try:
        with open(path) as f:
            return json.load(f)
    except Exception:
        return {}


def _read_gateway_errors() -> list[str]:
    """Grep ERROR|WARN from gateway log, last 200 lines."""
    if not GATEWAY_LOG.exists():
        return []
    try:
        result = subprocess.run(
            ["grep", "-iE", "error|warn|exception|traceback", str(GATEWAY_LOG)],
            capture_output=True,
            text=True,
            timeout=10,
        )
        lines = result.stdout.splitlines()
        return lines[-200:]
    except Exception:
        return []


def _read_robot_memory() -> str:
    """Read current robot-memory.md; create a minimal stub if absent."""
    if MEMORY_FILE.exists():
        try:
            return MEMORY_FILE.read_text()
        except Exception:
            return ""

    # Stub — will be replaced by first successful dream run.
    stub = (
        "# Robot Memory\n"
        "Generated by autoDream. Updated nightly.\n\n"
        "## Learnings\n(none yet)\n\n"
        "## Known Issues\n(none)\n"
    )
    try:
        OPENCASTOR_DIR.mkdir(parents=True, exist_ok=True)
        MEMORY_FILE.write_text(stub)
    except Exception:
        pass
    return stub


def _atomic_write(path: Path, content: str) -> None:
    """Write *content* to *path* atomically via a temp file + rename."""
    parent = path.parent
    parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(dir=parent, prefix=".autodream-tmp-")
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(tmp_path, path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except Exception:
            pass
        raise


def _append_dream_log(
    date_str: str,
    result: DreamResult,
    issue_urls: list[str] | None = None,
) -> None:
    """Append a structured entry to dream-log.jsonl."""
    entry = {
        "date": date_str,
        "learnings": result.learnings,
        "issues": result.issues_detected,
        "summary": result.summary,
        "issue_urls": issue_urls or [],
    }
    try:
        OPENCASTOR_DIR.mkdir(parents=True, exist_ok=True)
        with open(DREAM_LOG_FILE, "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception as exc:
        logger.warning("Could not append to dream-log.jsonl: %s", exc)


def _init_provider():
    """Initialise a provider from env/config for nightly use.

    Reads CASTOR_MODEL (default: claude-haiku-4-5-20251001) and the provider
    class from CASTOR_PROVIDER (default: anthropic).
    """
    model = os.getenv("CASTOR_MODEL", DEFAULT_MODEL)
    provider_name = os.getenv("CASTOR_PROVIDER", "anthropic")

    config: dict = {"model": model}

    try:
        from castor.providers import get_provider

        return get_provider(provider_name, config)
    except Exception as exc:
        raise RuntimeError(f"Could not initialise provider '{provider_name}': {exc}") from exc


def main() -> None:
    logging.basicConfig(level=logging.WARNING, format="%(levelname)s %(name)s: %(message)s")

    today = datetime.now().strftime("%Y-%m-%d")

    # 1. Load inputs
    health_report = _load_health_report(today)
    session_logs = _read_gateway_errors()
    robot_memory = _read_robot_memory()

    # 2. Build session
    session = DreamSession(
        session_logs=session_logs,
        robot_memory=robot_memory,
        health_report=health_report,
        date=today,
    )

    # 3. Init provider
    try:
        provider = _init_provider()
    except RuntimeError as exc:
        print(f"autoDream brain unavailable: {exc}", file=sys.stderr)
        sys.exit(1)

    # 4. Run dream brain
    brain = AutoDreamBrain(provider)
    result = brain.run(session)

    # 5. Atomic write of updated memory
    try:
        _atomic_write(MEMORY_FILE, result.updated_memory)
    except Exception as exc:
        print(f"autoDream: failed to write robot-memory.md: {exc}", file=sys.stderr)
        sys.exit(1)

    # 6. File GitHub issues for detected problems
    issue_urls: list[str] = []
    if result.issues_detected:
        repo = os.getenv("CASTOR_GITHUB_REPO", DEFAULT_GITHUB_REPO)
        rrn = os.getenv("CASTOR_RRN", "unknown")
        for issue_text in result.issues_detected:
            template = build_issue_template(issue_text, rrn, today)
            url = file_github_issue(template, repo, dry_run=DRY_RUN)
            if url:
                issue_urls.append(url)
        logger.info("autoDream filed %d issue(s)", len(issue_urls))

    # 7. Append to dream log
    _append_dream_log(today, result, issue_urls=issue_urls)

    # 8. Print summary to stdout (captured by autodream.sh)
    print(result.summary or f"autoDream {today}: complete")

    sys.exit(0)


if __name__ == "__main__":
    main()
